spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: temperatureModule
        uri: lb://TEMPERATURE-SERVICE
        predicates:
        - Path=/users/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
