server:
  port: 8082
spring:
  application:
    name: temperature-service
  cloud:
    stream:
      bindings:
        message-sink :
         destination: amq.topic
         binder: rabbit
         group: temperature-consumer-group 
         consumer :
           concurrency: 1
      rabbit:
        bindings:
          message-sink:
            consumer:
              bindQueue: true
              bindingRoutingKey: temperature 
              durableSubscription: true
              declareExchange: true
              exchangeDurable: true
              exchangeType: topic
              queueNameGroupOnly: true 
  rabbitmq:
    host: localhost
    password: password
    username: admin
  datasource:
    url: jdbc:mysql://localhost:3306/attivitaprogettuale?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
     hibernate:
       default_schema: schema
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true

