server:
  port: 8082
spring:
  application:
    name: temperature-service
  cache:
    jcache:
      config: classpath:ehcache.xml
  cloud:
    stream:
      bindings:
        message-sink :
         destination: amq.topic
         binder: rabbit
         group: temperature-consumer-group 
         consumer :
           concurrency: 1
      rabbit:
        bindings:
          message-sink:
            consumer:
              bindQueue: true
              bindingRoutingKey: temperature 
              durableSubscription: true
              declareExchange: true
              exchangeDurable: true
              exchangeType: topic
              queueNameGroupOnly: true 
  rabbitmq:
    host: localhost
    password: password
    username: admin
  datasource:
    url: jdbc:mysql://localhost:3306/attivitaprogettuale?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
     hibernate:
       default_schema: schema
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j.circuitbreaker:
    backends:
        userService:
            register-health-indicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 3
            permittedNumberOfCallsInHalfOpenState: 2
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 5000
            failureRateThreshold: 35
            ignoreExceptions:
                - org.springframework.dao.DataIntegrityViolationException
                - it.distributedsystems.projectactivity.temperatureservice.exception.UserNotFoundException
resilience4j.retry:
    instances:
        userService:
            maxRetryAttempts: 3
            waitDuration: 500
            ignoreExceptions:
                - org.springframework.dao.DataIntegrityViolationException
                - it.distributedsystems.projectactivity.temperatureservice.exception.UserNotFoundException

